twig:
    file_name_pattern: '*.twig'
    globals:
        backend_url: '%app.local_backend_url%'
        frontend_url: '%app.local_frontend_url%'

when@test:
    twig:
        strict_variables: true
